Increment 8
PostScripton/go-metrics-and-alerting-collection pull request #13
Opened 2022-08-11 22:01 UTC by PostScripton

2022-08-15 20:04 UTC, capsulated requested changes

2022-08-15 20:04 UTC, capsulated commented on internal/repository/file/file.go
> +func RunStoring(interval time.Duration, from repository.CollectionGetter, to *fileStorage) {
`func (*fileStorage) Run(...) `
Если он такой же, как и в memoryStorage - то встраивание

2022-08-15 20:04 UTC, capsulated commented on internal/repository/memory/memory.go
>  func New() *memoryStorage {
NewMemoryStorage() 

https://go.dev/doc/effective_go#composite_literals

2022-08-15 20:04 UTC, capsulated commented on internal/repository/repository.go
>  type CollectionGetter interface {
Я бы объединил всё в общий интерфейс **Repositorier**

2022-08-15 20:04 UTC, capsulated commented on internal/server/handlers/handler.go
>  func UpdateMetricHandler(storer repository.Storer) func(rw http.ResponseWriter, r *http.Request) {
Про хендлеры я уже писал

2022-08-15 20:04 UTC, capsulated commented on internal/server/handlers/handler_helpers.go
> +package handlers
И про хелперы писал в прошлых PR.

Прикрепить к структуре или встроить (инкапсулирование)

2022-08-15 20:04 UTC, capsulated commented on internal/server/handlers/json_handler.go
> +func UpdateMetricJSONHandler(storer repository.Storer) func(rw http.ResponseWriter, r *http.Request) {
Хендлеры инкапсулировать

2022-08-22 08:36 UTC, PostScripton commented on cmd/server/main.go
> +	router.Use(middleware.StripSlashes)
Сделал в предыдущих инкрементах

2022-08-22 08:36 UTC, PostScripton commented on internal/client/client.go
> +	gz := gzip.NewWriter(&out)
Это HTTP клиент для отправки метрики на сервер и он архивирует запрос

2022-08-22 08:36 UTC, PostScripton commented on cmd/agent/main.go
>  type Agent interface {
Сделал в предыдущих инкрементах

2022-08-22 08:36 UTC, PostScripton commented on cmd/server/main.go
> +func registerRoutes(router *chi.Mux, storage storager) {
Сделал в предыдущих инкрементах

2022-08-22 08:37 UTC, PostScripton commented on internal/repository/file/file.go
> +func New(path string) *fileStorage {
Сделал в предыдущих инкрементах. NewFileStorage

2022-08-22 08:37 UTC, PostScripton commented on internal/repository/memory/memory.go
>  func New() *memoryStorage {
Сделал в предыдущих инкрементах. NewMemoryStorage

2022-08-22 08:37 UTC, PostScripton commented on internal/repository/repository.go
>  type CollectionGetter interface {
Сделал в предыдущих инкрементах

2022-08-22 08:37 UTC, PostScripton commented on internal/server/handlers/handler.go
>  func UpdateMetricHandler(storer repository.Storer) func(rw http.ResponseWriter, r *http.Request) {
Сделал в предыдущих инкрементах

2022-08-22 08:37 UTC, PostScripton commented on internal/server/handlers/handler_helpers.go
> +package handlers
Объяснил в предыдущих инкрементах

2022-08-22 08:38 UTC, PostScripton commented on internal/server/handlers/json_handler.go
> +func UpdateMetricJSONHandler(storer repository.Storer) func(rw http.ResponseWriter, r *http.Request) {
Сделал в предыдущих инкрементах, в структуре сервера

2022-08-24 13:32 UTC, closed without merging