Sprint 3
PostScripton/go-metrics-and-alerting-collection pull request #18
Opened 2022-08-24 14:01 UTC by PostScripton

### Increment 10
В одном терминале запустить PostgreSQL:
```bash
docker-compose up --build
```
В другом запустить сервер:
```php
go run cmd/server/main.go -d=postgres://homestead:secret@localhost:5432/metrics_and_alerting
```

2022-09-14 16:34 UTC, capsulated requested changes
Видно, что время уделил организации структуры проекта, логике и взаимодействию структур. Написано классно, хорошо читается и отчётливо виден ход мыслей)

Написал комментариев - они относятся к организации связей между объектами. Можно с этим поиграться и сделать структуру проекта ещё более удобной для дальнейшего развития.

Предлагаю созвониться 1-1 - очень быстро объясню суть своих мыслей. А если я не увидел чего-то - также проясним)

2022-09-14 16:34 UTC, capsulated commented on internal/repository/database/postgres/postgres.go
> +package postgres
Я бы дополнительную папку `database` не стал бы создавать. Он подразумевает, что может быть множество баз дынных. Либо внутри пакета создал бы структуру `database`, которая реализует одну/несколько БД объектов. Кажется, что в остальных пакетах `file` и `memory` тоже подразумевается, что должны быть разные папке для нескольких реализаций.

Но это момент некритичный и спорный, тут конечно, обсуждать по-хорошему)

2022-09-14 16:34 UTC, capsulated commented on internal/repository/database/postgres/postgres.go
> +func ConnectToDB(ctx context.Context, dsn string) (*pgxpool.Pool, error) {
Статические методы в пакете со структурой, к которым относятся эти функции, может сделать методами этой структуры? Или есть какая-то задумка, которую я не уловил? 🤔

2022-09-14 16:34 UTC, capsulated commented on internal/agent/agent.go
`Runner` или `MetricAgentRunner` может лучше?)

А ещё можно что-то типа того (если, например, два агента создать):
```go
type AgentRunner interface {
	Run(interval time.Duration)
}

// Или
type AgentRunner interface {
	RunPooling(interval time.Duration)
	RunReporting(interval time.Duration)
}

// Или
// 
type PoolingRunner interface {
	PoolingRun(interval time.Duration)
}

type ReportingRunner interface {
	ReportingRun(interval time.Duration)
}

// И тп
```

Это всё же запускатор больше, хотя... Мысли, "на подумать")))

2022-09-14 16:34 UTC, capsulated commented on internal/server/server.go
> +func NewServer(address string, storage repository.Storager, key string, pool *pgxpool.Pool) *server {
`middlewares` из сервера вытащить можно, как независимый пакет. И передавать его в конструктор сервера. Опять же - это расчёт на то, чтобы сервер можно было заменить.

2022-09-14 16:34 UTC, capsulated commented on internal/server/server.go
> +func NewServer(address string, storage repository.Storager, key string, pool *pgxpool.Pool) *server {
А вот `pool *pgxpool.Pool` точно не нужно отдельным объектом передавать. Он должен быть методом базы. Либо специальный метод инкапсулировать в `repository.Storager` (если нужно, с проверкой типа хранилища), чтобы на сервер на своём уровне ничего не знал про реализацию пинга.

2022-09-19 15:10 UTC, PostScripton commented on internal/server/server.go
> +func NewServer(address string, storage repository.Storager, key string, pool *pgxpool.Pool) *server {
Не стал вытаскивать middlewares в отдельный пакет, т.к. используются ResponseWriter & Request, поэтому легко заменить не получится

2022-09-20 19:19 UTC, capsulated approved these changes
👌

2022-09-25 13:01 UTC, merged