Increment 3
PostScripton/go-metrics-and-alerting-collection pull request #3
Opened 2022-07-14 22:24 UTC by PostScripton

2022-07-15 15:58 UTC, PostScripton commented
Честно, я не знаю почему ругаются тесты со 2 инкремента.
У меня в постмане показывает на тот же url ошибку 404, как и нужно, а в тестах 307((

2022-07-15 16:00 UTC, PostScripton commented
Плюс подключить HTML-template по wildcard в Gin вообще не получилось, как бы я не пробовал: от cmd/server/main.go, от internal/server/service/service.go писать путь до шаблона - ничего не помогало, он выдаёт ошибку, что шаблонов нет

2022-07-19 15:13 UTC, capsulated requested changes
1) Не могу прокомментировать содержимое пакетов agent, client из internal, так как они уже влиты в sprint-1 😢 Не нужно вливать изменения в ветку, пока менторы не посмотрели весь код, так как не возможно прокомментировать некоторые части кода 😓 Можно создать новую ветку и туда залить самые последние изменения одним коммитом. И создать PR и отправить на ревью. Либо, влить все последние изменения в Sprint-1 и создать уже PR в main из него (самые последние изменения на чистый проект)

2) Везде перепроверить, что передаются указатели на структуры, где это необходимо, чтобы не копировались экземпляры. В бОльшей степени это касается больших объектов/структур

2022-07-19 15:13 UTC, capsulated commented on internal/metrics/metrics.go
>  package metrics
Не могу прокомментировать содержимое пакетов agent, client из internal, так как они уже влиты в sprint-1 😢 Не нужно вливать изменения в ветку, пока менторы не посмотрели весь код, так как не возможно прокомментировать некоторые части кода 😓 Можно создать новую ветку и туда залить самые последние изменения одним коммитом. И создать PR и отправить на ревью.

Влить все последние изменения в Sprint-1 и создать уже PR в main из него (самые последние изменения на чистый проект)

2022-07-19 15:13 UTC, capsulated commented on internal/metrics/metrics.go
>  package metrics
Также, не могу конструкторы и типы прокомментировать 😓

В текущем задании даже излишне создавать новые типы
Но, в тоже время, может быть ситуация в будущем, что понадобится
Тут можно и алиасы, в принципе, применить
```
type Gauge = float64 // алиас
type Gauge float64 // или новый тип
```

2022-07-19 15:13 UTC, capsulated commented on internal/repository/memory/memory.go
>  	return storage.gaugeMetrics
Начало файла не могу коментить =(

Можно и в самом начале интерфейсы определять, не перенося их в отдельный пакет
Как пример - стандартные пакеты go

2022-07-19 17:54 UTC, merged