Sprint 1
PostScripton/go-metrics-and-alerting-collection pull request #4
Opened 2022-07-21 18:24 UTC by PostScripton

2022-07-23 15:04 UTC, capsulated requested changes
Ещё несколько исправлений и будет отлично.

2022-07-23 15:04 UTC, capsulated commented on internal/agent/service/service.go
> +package service
Если глянуть пакет **net/http** там даже директорий нет под **server**, **client**. Просто файлы _server.go_, _client.go_ в корне пакета. А у сервера нету даже структуры и конструктора.

Но, в тоже время, пакет **http** вложен в **net**. 

Очень советую поизучать, как написаны стандартные пакеты **go** внутри.

2022-07-23 15:04 UTC, capsulated commented on internal/server/service/service.go
> +package service
Также, имя пакета service не даёт точного понимания, что он делает. Это обобщающее имя и структуре может происходить что угодно.

2022-07-23 16:35 UTC, PostScripton commented on internal/metrics/metrics.go
> +func (c Counter) String() string {
Насколько я знаю - ресивер типа указатель или типа значения, не имеют разницы, если поля структуры не изменяются.

Если мы хотим, чтобы изменения, производимые в методе, отразились на данных структуры, тогда будем использовать ревисер по указателю.

В данном примере, мы просто получаем данные, но не изменяем их, поэтому тут без разницы какой ресивер. Поправьте, если я не прав))

2022-07-23 16:50 UTC, PostScripton commented on internal/repository/memory/memory.go
> +	storage.mu.Lock()
Хах, да, затупил, спасибо)

2022-07-23 16:54 UTC, PostScripton commented on internal/repository/memory/memory.go
> +func (storage *memoryStorage) Get(t string, name string) (metrics.MetricType, error) {
Просто я где-то вычитал (вроде из слака ссылка была), что раз где-то нужен именно указатель на структуру, то все другие методы должны быть указателями на структуру, общий вид, даже если это не нужно.

Не знаю насколько это правда)

2022-07-25 20:02 UTC, capsulated commented on internal/metrics/metrics.go
> +func (c Counter) String() string {
Да, для типов указатель не нужен, в такой конфигурации, как у нас 👍🔥

2022-07-25 20:06 UTC, capsulated approved these changes
Всё отлично!
В результате получился хорошо читаемый код. Его в дальнейшем будет удобно дорабатывать, работая над ним, внедряя новый функционал. Супер! 👍👍🔥

2022-07-26 18:16 UTC, merged