Increment 4
PostScripton/go-metrics-and-alerting-collection pull request #7
Opened 2022-08-02 21:48 UTC by PostScripton

2022-08-15 19:29 UTC, capsulated requested changes
Пакеты немного переформировать и станет вообще идеально!

2022-08-15 19:29 UTC, capsulated commented on cmd/server/main.go
> +type storager interface {
Интерфейс в пакет репозитория перенести нужно. В cmd такое не нужно)

2022-08-15 19:29 UTC, capsulated commented on cmd/server/main.go
> +	router.Use(middleware.StripSlashes)
Роутер в пакет сервера перенести. В cmd только вызов конструкторов, запуск воркеров и ловить сигналы системы (если надо)

2022-08-15 19:29 UTC, capsulated commented on cmd/server/main.go
> +func registerRoutes(router *chi.Mux, storage storager) {
Перенести в пакет Server или Routes или Handlers.

2022-08-15 19:29 UTC, capsulated commented on internal/server/handlers/handler.go
>  func UpdateMetricHandler(storer repository.Storer) func(rw http.ResponseWriter, r *http.Request) {
Например, тут, как раз структуру, для хендлеров. И конструктор с биндинга хендлеров. И вызывать NewHendlers в cmd. Или в Server. 🤔

2022-08-15 19:29 UTC, capsulated commented on internal/server/handlers/json_handler.go
> +var notFoundResponse = JSONObj{"message": "404 page not found"}
**const**

2022-08-15 19:29 UTC, capsulated commented on internal/server/handlers/json_handler.go
> +var methodNotAllowed = JSONObj{"message": "405 method not allowed"}
и тут)

2022-08-15 19:29 UTC, capsulated commented on internal/server/handlers/handler_helpers.go
> +package handlers
Как-то меня смущает пакет **helpers** 😁

Нужно уходить от таких конструкций, типа **helpers**, **utils**, **service**. 
1) Это очень плохой нейминг
2) Лучше подобные методы добавлять к той структуре, в которых они используются
3) Если одинаковые методы используются в нескольких пакетах/структурах, то создать структуру с этими методами и встраивать её

2022-08-15 19:29 UTC, capsulated commented on internal/server/handlers/json_handler.go
> +func UpdateMetricJSONHandler(storer repository.Storer) func(rw http.ResponseWriter, r *http.Request) {
Опять же, прикрутить к структуре сервера или хендлера

2022-08-18 19:42 UTC, PostScripton commented on internal/server/handlers/handler_helpers.go
> +package handlers
Так пакет `handlers`, а в этом файле функции, которые помогают обрабатывать HTTP ответы

2022-08-18 20:48 UTC, PostScripton commented on internal/server/handlers/handler_helpers.go
> +package handlers
UPD: переделал и теперь это под пакетом server

2022-08-24 13:32 UTC, closed without merging