Update metrics storage method
PostScripton/go-metrics-and-alerting-collection pull request #9
Opened 2022-08-07 20:09 UTC by PostScripton

2022-08-15 19:46 UTC, capsulated requested changes

2022-08-15 19:46 UTC, capsulated commented on internal/metrics/metrics.go
>  var ErrNoValue = errors.New("no value")
**const** может всё же? разве **goland** не ругается?

2022-08-15 19:46 UTC, capsulated commented on internal/metrics/metrics.go
> +func New(t string, name string) *Metrics {
**NewMetric**() ? А он вообще тут нужен? Может ограничиться Counter и Guage?

2022-08-15 19:46 UTC, capsulated commented on internal/metrics/metrics.go
> +func NewCounter(name string, delta int64) *Metrics {
**NewCounterMetric**() ?

Кстати, насчёт множественного числа))) Если возвращается массив, то Metrics. Если единственная структура: то Metric. Но это для конструкторов и названия методов/функций. 

Для пакетов - в зависимости от контекста (здравого смысла 🙂)

2022-08-15 19:46 UTC, capsulated commented on internal/repository/repository.go
>  type CollectionGetter interface {
Getter, Storer и и тп. Так их много и тяжело ориентироваться

Может один интерфейс сделать для репозитория? И назвать Repositorier? )))

2022-08-15 19:46 UTC, capsulated commented on internal/server/handlers/handler.go
>  			if err != nil {
Вообще хендлер тоже можно не выносить в отдельный пакет. Но в отдельную структуру, и можно в отдельный файл в пакете сервера. Типа NewHendler(s)

2022-08-18 21:15 UTC, PostScripton commented on internal/metrics/metrics.go
>  var ErrNoValue = errors.New("no value")
Goland как раз ругается на const, потому что нельзя присваивать динамические вещи, такие как вызов функции, например

2022-08-18 21:17 UTC, PostScripton commented on internal/metrics/metrics.go
> +func New(t string, name string) *Metrics {
Эта функция нужна, чтобы возвращать метрику без значений, к примеру, для передачи на сервер в качестве запроса. Создавать через структуру неудобно, а через такую функцию красиво

2022-08-18 21:22 UTC, PostScripton commented on internal/repository/memory/memory.go
> +func (s *memoryStorage) Get(metric metrics.Metrics) (*metrics.Metrics, error) {
Это тогда придётся менять в интерфейсах и тд., хотя оно и так для меня читается.
Можно не надо?))
👉🏻👈🏻 

Но замечание я услышал, согласен

2022-08-18 21:23 UTC, PostScripton commented on internal/server/handlers/handler.go
>  			if err != nil {
Сделал в предыдущих ПР-ах

2022-08-24 13:32 UTC, closed without merging